package main

import (
	"log"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "ms-operations/docs" // Docs generated by Swag CLI
	"ms-operations/internal/database"
	"ms-operations/internal/handlers"
	"ms-operations/internal/middleware"
)

// @title           MS Operations API
// @version         1.0
// @description     API para operaciones del sistema SistaL.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8083
// @BasePath  /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Token de autenticación JWT en formato Bearer

func main() {
	// Load environment variables
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found, relying on system env variables")
	}

	// Connect to database
	database.Connect()

	// Setup Gin router
	r := gin.Default()

	// Health check - sin autenticación
	r.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status": "up",
		})
	})

	// Swagger - sin autenticación
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API v1 - todas las rutas con autenticación
	v1 := r.Group("/api/v1")
	v1.Use(middleware.AuthMiddleware())
	{
		// Peticiones de Uniformes
		peticiones := v1.Group("/peticiones")
		{
			peticiones.GET("", handlers.GetPeticiones)
			peticiones.GET("/:id_peticion", handlers.GetPeticionByID)
			peticiones.POST("", handlers.CreatePeticion)
			peticiones.PUT("/:id_peticion", handlers.UpdatePeticion)
			peticiones.PATCH("/:id_peticion/estado", handlers.CambiarEstadoPeticion)
			peticiones.GET("/:id_peticion/tallaje", handlers.GetTallajePeticion)
		}

		// Despachos
		despachos := v1.Group("/despachos")
		{
			despachos.GET("", handlers.GetDespachos)
			despachos.GET("/:id_despacho", handlers.GetDespachoByID)
			despachos.POST("", handlers.CreateDespacho)
			despachos.PUT("/:id_despacho", handlers.UpdateDespacho)
			despachos.PATCH("/:id_despacho/estado", handlers.CambiarEstadoDespacho)
		}

		// Facturas
		facturas := v1.Group("/facturas")
		{
			facturas.GET("", handlers.GetFacturas)
			facturas.POST("", handlers.CreateFactura)
		}

		// Catálogos
		v1.GET("/tipos-peticion", handlers.GetTiposPeticion)

		// Operaciones (estadísticas y dashboard)
		operaciones := v1.Group("/operaciones")
		{
			operaciones.GET("/estadisticas", handlers.GetEstadisticasOperaciones)
			operaciones.GET("/dashboard", handlers.GetDashboardOperaciones)
		}

		// Notificaciones (deprecado - migrar a MS-Notifications)
		v1.GET("/notificaciones", handlers.GetNotifications)
	}

	// Run server
	port := os.Getenv("SERVER_PORT")
	if port == "" {
		port = "8083"
	}
	log.Printf("Starting MS-Operations server on port %s", port)
	if err := r.Run(":" + port); err != nil {
		log.Fatal("Server failed to start:", err)
	}
}
